apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  containers:
    - name: redis
      image: redis:6.2.5
      ports:
        - containerPort: 6379         
          protocol: TCP
